---
- name: install pacman packages
  pacman:
    name:
      - fish
      - git
      - tmux
      - yay
      - rofi
      - python-pip
      - python-setuptools
      - python-virtualenv
      - dnsutils
      - gcc
      - nodejs
      - npm
      - strace
      - jq
      - ripgrep
      - zip
      - unzip
      - discord
      - vlc
      - obs-studio
      - xclip
      - stack
      - feh # image preview

- name: set ntp
  command: timedatectl set-timezone Asia/Tokyo

- name: set timezone
  command: timedatectl set-ntp true
