# depends manjaro-root (xprofile)

- name: install AUR packages
  aur:
    name:
      - ttf-mplus
      - git-now-git

- name: create config directory
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "/home/{{ ansible_user }}/.config/fish/fuctions/"
    - "/home/{{ ansible_user }}/.config/ranger/"
    - "/home/{{ ansible_user }}/.config/rofi/"

- name: hardcopy config files
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    backup: yes
  with_items:
    # TODO: put these on roles/templates
    - src:  "../../../../.tmux.conf"
      dest: "/home/{{ ansible_user }}/.tmux.conf"
    - src:  "../../../../.xprofile"
      dest: "/home/{{ ansible_user }}/.xprofile"
    - src: "../../../../.gitignore_global"
      dest: "/home/{{ ansible_user }}/.gitignore_global"
    # - src: "../../../../.gitconfig"
      # dest: "/home/{{ ansible_user }}/.gitconfig"
