- name: install AUR packages
  aur:
    name:
      - google-chrome
      - ttf-mplus

- name: create config directory
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "/home/{{ ansible_user }}/.config/fish/fuctions/"
    - "/home/{{ ansible_user }}/.config/ranger/"
    - "/home/{{ ansible_user }}/.i3/"
    - "/home/{{ ansible_user }}/.config/rofi/"

- name: hardcopy config files
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    backup: yes
  with_items:
    # TODO: put these on roles/templates
    - src:  "../../../../.tmux.conf"
      dest: "/home/{{ ansible_user }}/.tmux.conf"
