---
- hosts: localhost
  roles:
    - { role: "manjaro-root", become: yes }
    - { role: "manjaro-user" }
    - { role: "xkeysnail" }
    - { role: "neovim" }
    - { role: "i3wm" }
    - { role: "font" }
    - { role: "urxvt" }
    - { role: "fcitx" }
    - { role: "fish" }
  vars:
    - ansible_user: "ahy" #????
